In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

In [3]:
print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[6 1 4]
 [4 8 4]
 [6 3 5]]
Matrix B:
 [[8 7 9]
 [9 2 7]
 [8 8 9]]


In [4]:
addi = A + B
print("A + B:\n", addi)

A + B:
 [[14  8 13]
 [13 10 11]
 [14 11 14]]


In [5]:
sub = A - B
print("A - B:\n", sub)


A - B:
 [[-2 -6 -5]
 [-5  6 -3]
 [-2 -5 -4]]


In [7]:
multi = A @ B
print("A x B:\n", multi)

A x B:
 [[ 89  76  97]
 [136  76 128]
 [115  88 120]]


In [8]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 28.00000000000001


In [9]:
if det_A != 0:
    inverse_A = np.linalg.inv(A)
    print("Inverse of A:\n", inverse_A)
else:
    print("Matrix A is not invertible")


Inverse of A:
 [[ 1.          0.25       -1.        ]
 [ 0.14285714  0.21428571 -0.28571429]
 [-1.28571429 -0.42857143  1.57142857]]


In [10]:
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

Rank of A: 3
